name: test

on:
  workflow_dispatch
  
jobs:
  post-reminder:
    name: Post reminder to carbon-react
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "username": "Test workflow",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "@taylor",
              "text": "Test",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Join us for Carbon Developer Office Hours!",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "image",
                  "image_url": "https://carbondesignsystem.com/static/406b7e7bf6865c094dd9a7a0bcb8bd41/3cbba/light-getting-started-developers.png",
                  "alt_text": "A terminal prompt symbol"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "_Are you running into a weird bug you can’t resolve?_ :thinking_face:  _Do you want some help using Carbon v10 or v11?_ :handshake: \n\n\n *Carbon developer office hours* are a bi-weekly opportunity to ask questions and get help from the team. Developers from the Carbon System Squad, who maintain the core React components, elements and styles, will be available to help."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":yourlearning:  *Subscribe, add to your calendar, attend the next meeting*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Subscribe",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ec.yourlearning.ibm.com/w3/enrollment/event/10289726",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":memo:  *Sign up to get help in a future session*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View the agenda",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ibm.biz/carbon-dev-office-hours",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
