name: test

on:
  workflow_dispatch
  
jobs:
  post-reminder:
    name: Post reminder to carbon-react
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "username": "Test workflow",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "@taylor",
              "text": "Test",
              "blocks": [
                {
                  "type": "image",
                  "image_url": "https://carbondesignsystem.com/static/406b7e7bf6865c094dd9a7a0bcb8bd41/3cbba/light-getting-started-developers.png",
                  "alt_text": "A terminal prompt symbol"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "TESTING",
                    "emoji": true
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
